In [101]:
import pandas as pd

In [102]:
tax_bracket_df = pd.read_csv('data/historical_tax_brackets.csv').drop(columns=['Unnamed: 2', 'Unnamed: 5', 'Unnamed: 8', 'Unnamed: 11', 'Notes:'])
tax_bracket_df = tax_bracket_df[["Year","Single Filer (Rates/Brackets)","Unnamed: 9","Head of Household (Rates/Brackets)","Unnamed: 12","Married Filing Jointly (Rates/Brackets)","Unnamed: 3","Married Filing Separately (Rates/Brackets)","Unnamed: 6"]]
tax_bracket_df.columns=['year', 'single_r', 'single_bs', 'hoh_r', 'hoh_bs', 'mfj_r', 'mfj_bs', 'mfs_r', 'mfs_bs']

rate_cols = [c for c in tax_bracket_df.columns if c.endswith('_r')]
backet_start_cols = [c for c in tax_bracket_df.columns if c.endswith('_bs')]

tax_bracket_df[rate_cols] = tax_bracket_df[rate_cols].apply(lambda x: pd.to_numeric(x.str.rstrip('%'), errors='coerce') / 100)
tax_bracket_df[backet_start_cols] = tax_bracket_df[backet_start_cols].apply(lambda x: pd.to_numeric(x.replace(r'[$,]', '', regex=True), errors='coerce'))

tax_bracket_df = tax_bracket_df.dropna(how='all').fillna(0)

tax_bracket_df.head()

,year,single_r,single_bs,hoh_r,hoh_bs,mfj_r,mfj_bs,mfs_r,mfs_bs
0,2025,0.10,0.0,0.10,0.0,0.10,0.0,0.10,0.0
1,2025,0.12,11925.0,0.12,17000.0,0.12,23850.0,0.12,11925.0
2,2025,0.22,48475.0,0.22,64850.0,0.22,96950.0,0.22,48475.0
3,2025,0.24,103350.0,0.24,103350.0,0.24,206700.0,0.24,103350.0
4,2025,0.32,197300.0,0.32,197300.0,0.32,394600.0,0.32,197300.0

In [103]:
cpi_df = pd.read_csv('data/january_cpi_1913_to_2026.csv')
cpi_df['inflation_adj_ratio'] = cpi_df['cpi'][0] / cpi_df['cpi']

cpi_df.head()

   year      cpi  inflation_adj_ratio
0  2026  325.252             1.000000
1  2025  317.671             1.023864
2  2024  308.417             1.054585
3  2023  299.170             1.087181
4  2022  281.148             1.156871