In [40]:
import pandas as pd

In [41]:
tax_bracket_df = pd.read_csv('data/historical_tax_brackets.csv')

tax_bracket_df.head()

,Year,Married Filing Jointly (Rates/Brackets),Unnamed: 2,Unnamed: 3,Married Filing Separately (Rates/Brackets),Unnamed: 5,Unnamed: 6,Single Filer (Rates/Brackets),Unnamed: 8,Unnamed: 9,Head of Household (Rates/Brackets),Unnamed: 11,Unnamed: 12,Notes:
0,2025,10.0%,>,$0,10.0%,>,$0,10.0%,>,$0,10.0%,>,$0,Last law to change rates was the Tax Cuts and ...
1,2025,12.0%,>,"$23,850",12.0%,>,"$11,925",12.0%,>,"$11,925",12.0%,>,"$17,000",NaN
2,2025,22.0%,>,"$96,950",22.0%,>,"$48,475",22.0%,>,"$48,475",22.0%,>,"$64,850",NaN
3,2025,24.0%,>,"$206,700",24.0%,>,"$103,350",24.0%,>,"$103,350",24.0%,>,"$103,350",NaN
4,2025,32.0%,>,"$394,600",32.0%,>,"$197,300",32.0%,>,"$197,300",32.0%,>,"$197,300",NaN

In [42]:
cpi_df = pd.read_csv('data/january_cpi_1913_to_2026.csv')

cpi_df.head()

   year   cpi
0  1913   9.8
1  1914  10.0
2  1915  10.1
3  1916  10.4
4  1917  11.7